/*
 * This file is generated by jOOQ.
 */
package ru.skwardlow.database.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.TableImpl;

import ru.skwardlow.database.DefaultSchema;
import ru.skwardlow.database.tables.records.ManagersRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Managers extends TableImpl<ManagersRecord> {

    private static final long serialVersionUID = 1758351308;

    /**
     * The reference instance of <code>Managers</code>
     */
    public static final Managers MANAGERS = new Managers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ManagersRecord> getRecordType() {
        return ManagersRecord.class;
    }

    /**
     * The column <code>Managers.id</code>.
     */
    public final TableField<ManagersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>Managers.fio</code>.
     */
    public final TableField<ManagersRecord, String> FIO = createField("fio", org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>Managers.phone</code>.
     */
    public final TableField<ManagersRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(15).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>Managers.mailbox</code>.
     */
    public final TableField<ManagersRecord, String> MAILBOX = createField("mailbox", org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.inline("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>Managers</code> table reference
     */
    public Managers() {
        this(DSL.name("Managers"), null);
    }

    /**
     * Create an aliased <code>Managers</code> table reference
     */
    public Managers(String alias) {
        this(DSL.name(alias), MANAGERS);
    }

    /**
     * Create an aliased <code>Managers</code> table reference
     */
    public Managers(Name alias) {
        this(alias, MANAGERS);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased) {
        this(alias, aliased, null);
    }

    private Managers(Name alias, Table<ManagersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ManagersRecord, Integer> getIdentity() {
        return Internal.createIdentity(ru.skwardlow.database.tables.Managers.MANAGERS, ru.skwardlow.database.tables.Managers.MANAGERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ManagersRecord> getPrimaryKey() {
        return Internal.createUniqueKey(ru.skwardlow.database.tables.Managers.MANAGERS, "KEY_Managers_PRIMARY", ru.skwardlow.database.tables.Managers.MANAGERS.ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ManagersRecord>> getKeys() {
        return Arrays.<UniqueKey<ManagersRecord>>asList(
              Internal.createUniqueKey(ru.skwardlow.database.tables.Managers.MANAGERS, "KEY_Managers_PRIMARY", ru.skwardlow.database.tables.Managers.MANAGERS.ID)
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(String alias) {
        return new Managers(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Managers as(Name alias) {
        return new Managers(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(String name) {
        return new Managers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Managers rename(Name name) {
        return new Managers(name, null);
    }
}
