/*
 * This file is generated by jOOQ.
 */
package ru.skwardlow.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Langs implements Serializable {

    private static final long serialVersionUID = -256774563;

    private final Integer id;
    private final String  lang;

    public Langs(Langs value) {
        this.id = value.id;
        this.lang = value.lang;
    }

    public Langs(
        Integer id,
        String  lang
    ) {
        this.id = id;
        this.lang = lang;
    }

    public Integer getId() {
        return this.id;
    }

    public String getLang() {
        return this.lang;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Langs (");

        sb.append(id);
        sb.append(", ").append(lang);

        sb.append(")");
        return sb.toString();
    }
}
