/*
 * This file is generated by jOOQ.
 */
package ru.skwardlow.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Salesunity implements Serializable {

    private static final long serialVersionUID = -1799218548;

    private final Integer idMan;
    private final Integer idSale;

    public Salesunity(Salesunity value) {
        this.idMan = value.idMan;
        this.idSale = value.idSale;
    }

    public Salesunity(
        Integer idMan,
        Integer idSale
    ) {
        this.idMan = idMan;
        this.idSale = idSale;
    }

    public Integer getIdMan() {
        return this.idMan;
    }

    public Integer getIdSale() {
        return this.idSale;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Salesunity (");

        sb.append(idMan);
        sb.append(", ").append(idSale);

        sb.append(")");
        return sb.toString();
    }
}
