/*
 * This file is generated by jOOQ.
 */
package ru.skwardlow.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import ru.skwardlow.database.tables.Langunity;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LangunityRecord extends TableRecordImpl<LangunityRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1719833187;

    /**
     * Setter for <code>LangUnity.id_Dev</code>.
     */
    public void setIdDev(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LangUnity.id_Dev</code>.
     */
    public Integer getIdDev() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LangUnity.id_Lang</code>.
     */
    public void setIdLang(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>LangUnity.id_Lang</code>.
     */
    public Integer getIdLang() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Langunity.LANGUNITY.ID_DEV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Langunity.LANGUNITY.ID_LANG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getIdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdDev();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIdLang();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangunityRecord value1(Integer value) {
        setIdDev(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangunityRecord value2(Integer value) {
        setIdLang(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LangunityRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LangunityRecord
     */
    public LangunityRecord() {
        super(Langunity.LANGUNITY);
    }

    /**
     * Create a detached, initialised LangunityRecord
     */
    public LangunityRecord(Integer idDev, Integer idLang) {
        super(Langunity.LANGUNITY);

        set(0, idDev);
        set(1, idLang);
    }
}
