/*
 * This file is generated by jOOQ.
 */
package ru.skwardlow.database.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import ru.skwardlow.database.tables.Sales;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SalesRecord extends UpdatableRecordImpl<SalesRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 679484239;

    /**
     * Setter for <code>Sales.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>Sales.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>Sales.sale</code>.
     */
    public void setSale(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>Sales.sale</code>.
     */
    public String getSale() {
        return (String) get(1);
    }

    /**
     * Setter for <code>Sales.cost</code>.
     */
    public void setCost(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>Sales.cost</code>.
     */
    public String getCost() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Sales.SALES.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Sales.SALES.SALE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Sales.SALES.COST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSale();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCost();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalesRecord value2(String value) {
        setSale(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalesRecord value3(String value) {
        setCost(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SalesRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SalesRecord
     */
    public SalesRecord() {
        super(Sales.SALES);
    }

    /**
     * Create a detached, initialised SalesRecord
     */
    public SalesRecord(Integer id, String sale, String cost) {
        super(Sales.SALES);

        set(0, id);
        set(1, sale);
        set(2, cost);
    }
}
